"""description_of_changes

Revision ID: 6bc0dc58127b
Revises: '0003_dynamic_coupons_and_pricing'
Create Date: 2026-08-13 23:02:41.342568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bc0dc58127b'
down_revision: Union[str, None] = '0003_dynamic_coupons_and_pricing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'discount_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'percentage'"))
    op.drop_index(op.f('code'), table_name='coupons')
    op.add_column('search_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('search_history', 'timestamp')
    op.drop_index(op.f('email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.add_column('search_history', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('search_history', 'created_at')
    op.create_index(op.f('code'), 'coupons', ['code'], unique=True)
    op.alter_column('coupons', 'discount_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'percentage'"))
    # ### end Alembic commands ###
